# Created using wingetcreate 1.2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Instalator.Szafir.KIR.Graphite
PackageVersion: 2.6.684
PackageLocale: en-pl
Publisher: Krajowa Izba Rozliczeniowa S.A.
PublisherUrl: https://www.elektronicznypodpis.pl
PublisherSupportUrl: https://www.elektronicznypodpis.pl/kontakt/dane-kontaktowe/
PrivacyUrl: https://www.elektronicznypodpis.pl/kontakt/dane-kontaktowe/
Author: KIR
PackageName: Instalator Szafir
PackageUrl: https://www.elektronicznypodpis.pl/informacje/aplikacje/
License: KIR
LicenseUrl: https://www.elektronicznypodpis.pl/informacje/certyfikaty-i-listy-crl/
Copyright: https://www.elektronicznypodpis.pl/informacje/podstawy-prawne/
CopyrightUrl: https://www.elektronicznypodpis.pl/informacje/podstawy-prawne/
ShortDescription: Pakiet instalacyjny Szafir dla nowych kart Graphite
Description: Pakiet instalacyjny Szafir dla nowych kart Graphit
Tags:
- podpis
- szafir
- kir
- cryptocard
- kwalifikowany
- certyfikat
ManifestType: defaultLocale
ManifestVersion: 1.4.0
